<xsl:stylesheet
  version="3.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:oai-pmh="http://www.openarchives.org/OAI/2.0/"
  xmlns:oai_qdc="http://worldcat.org/xmlschemas/qdc-1.0/"
  xmlns:dcterms="http://purl.org/dc/terms/"
  xmlns:dcmitype="http://purl.org/dc/dcmitype/"
  xmlns:edm="http://www.europeana.eu/schemas/edm/"
  xmlns:oclcdc="http://worldcat.org/xmlschemas/oclcdc-1.0/"
  xmlns:mods="http://www.loc.gov/mods/v3"
  exclude-result-prefixes="xs"
  xpath-default-namespace="http://www.openarchives.org/OAI/2.0/"
  expand-text="yes">

<xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>


<!-- 
     This XSLT is intended to remove records from an XML file where
     the records have more than or fewer than one edm:rights value.
     This should be run against a "transformed" XML file, where 
     "transformed" == "generated by the set's filter transform(s)".
-->

<xsl:mode on-no-match="shallow-copy"/>

  <xsl:template match="record[not(count(./metadata/oai_qdc:qualifieddc/edm:rights)=1)]"/>

</xsl:stylesheet>

